import { SearchResult, ImageResult, VideoResult, NewsResult, MapResult } from '../types';

// Mock web search results
export const mockSearchResults: SearchResult[] = [
  {
    id: '1',
    title: 'What are bugs in software? - Definition from TechTarget',
    url: 'https://www.techtarget.com/searchsoftwarequality/definition/bug',
    displayUrl: 'www.techtarget.com › definition › bug',
    snippet: 'A software bug is an error, flaw or fault in a computer program or system that causes it to produce an incorrect or unexpected result, or to behave in unintended ways.',
    imageUrl: 'https://images.pexels.com/photos/207580/pexels-photo-207580.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: '2',
    title: 'How to Identify and Fix Common Coding Bugs - FreeCodeCamp',
    url: 'https://www.freecodecamp.org/news/identifying-and-fixing-common-coding-bugs/',
    displayUrl: 'www.freecodecamp.org › news › identifying-and-fixing-common-coding-bugs',
    snippet: 'Learn how to identify and fix the most common bugs in your code. This comprehensive guide covers debugging techniques for JavaScript, Python, and more.',
    imageUrl: 'https://images.pexels.com/photos/4709289/pexels-photo-4709289.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: '3',
    title: 'Debugging in Visual Studio Code',
    url: 'https://code.visualstudio.com/docs/editor/debugging',
    displayUrl: 'code.visualstudio.com › docs › editor › debugging',
    snippet: 'Debugging is a core feature of Visual Studio Code. In this article, we will take a closer look at the debugging capabilities of VS Code.',
  },
  {
    id: '4',
    title: 'The History of Software Bugs - IEEE Spectrum',
    url: 'https://spectrum.ieee.org/the-history-of-software-bugs',
    displayUrl: 'spectrum.ieee.org › the-history-of-software-bugs',
    snippet: 'From the first actual bug found in the Mark II computer to modern security vulnerabilities, this article traces the fascinating history of software bugs.',
    imageUrl: 'https://images.pexels.com/photos/459653/pexels-photo-459653.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: '5',
    title: 'Bug Tracking Software | Issue & Project Tracking | Jira',
    url: 'https://www.atlassian.com/software/jira/bug-tracking',
    displayUrl: 'www.atlassian.com › software › jira › bug-tracking',
    snippet: 'Jira\'s bug tracking software helps your team find and fix bugs faster. Customize your workflow, collaborate, and release with confidence.',
  },
  {
    id: '6',
    title: 'Common Web Development Bugs and How to Fix Them - CSS-Tricks',
    url: 'https://css-tricks.com/common-web-development-bugs-and-fixes/',
    displayUrl: 'css-tricks.com › common-web-development-bugs-and-fixes',
    snippet: 'This article covers the most common bugs in web development and provides solutions to fix them, from CSS layout issues to JavaScript runtime errors.',
    imageUrl: 'https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
];

// Mock image search results
export const mockImageResults: ImageResult[] = [
  {
    id: '1',
    title: 'Colorful Code on Screen',
    url: 'https://images.pexels.com/photos/577585/pexels-photo-577585.jpeg',
    thumbnailUrl: 'https://images.pexels.com/photos/577585/pexels-photo-577585.jpeg?auto=compress&cs=tinysrgb&w=600',
    sourceUrl: 'https://www.pexels.com/photo/colorful-code-on-screen-577585/',
    width: 1920,
    height: 1080,
  },
  {
    id: '2',
    title: 'Computer Bug Concept',
    url: 'https://images.pexels.com/photos/459653/pexels-photo-459653.jpeg',
    thumbnailUrl: 'https://images.pexels.com/photos/459653/pexels-photo-459653.jpeg?auto=compress&cs=tinysrgb&w=600',
    sourceUrl: 'https://www.pexels.com/photo/computer-bug-concept-459653/',
    width: 1200,
    height: 800,
  },
  {
    id: '3',
    title: 'Developer Debugging Code',
    url: 'https://images.pexels.com/photos/4709289/pexels-photo-4709289.jpeg',
    thumbnailUrl: 'https://images.pexels.com/photos/4709289/pexels-photo-4709289.jpeg?auto=compress&cs=tinysrgb&w=600',
    sourceUrl: 'https://www.pexels.com/photo/developer-debugging-code-4709289/',
    width: 1600,
    height: 900,
  },
  {
    id: '4',
    title: 'Software Development Team',
    url: 'https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg',
    thumbnailUrl: 'https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=600',
    sourceUrl: 'https://www.pexels.com/photo/software-development-team-3183150/',
    width: 1800,
    height: 1200,
  },
  {
    id: '5',
    title: 'Code on Laptop Screen',
    url: 'https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg',
    thumbnailUrl: 'https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&cs=tinysrgb&w=600',
    sourceUrl: 'https://www.pexels.com/photo/code-on-laptop-screen-574071/',
    width: 1920,
    height: 1080,
  },
  {
    id: '6',
    title: 'Programming Code Abstract',
    url: 'https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg',
    thumbnailUrl: 'https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&w=600',
    sourceUrl: 'https://www.pexels.com/photo/programming-code-abstract-546819/',
    width: 1600,
    height: 1067,
  },
  {
    id: '7',
    title: 'Debugging on Multiple Screens',
    url: 'https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg',
    thumbnailUrl: 'https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg?auto=compress&cs=tinysrgb&w=600',
    sourceUrl: 'https://www.pexels.com/photo/debugging-on-multiple-screens-1181263/',
    width: 1920,
    height: 1080,
  },
  {
    id: '8',
    title: 'Close-up of Programming Code',
    url: 'https://images.pexels.com/photos/270404/pexels-photo-270404.jpeg',
    thumbnailUrl: 'https://images.pexels.com/photos/270404/pexels-photo-270404.jpeg?auto=compress&cs=tinysrgb&w=600',
    sourceUrl: 'https://www.pexels.com/photo/close-up-of-programming-code-270404/',
    width: 1920,
    height: 1280,
  },
];

// Mock video search results
export const mockVideoResults: VideoResult[] = [
  {
    id: '1',
    title: 'How to Debug Like a Pro',
    url: 'https://www.youtube.com/watch?v=example1',
    thumbnailUrl: 'https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg?auto=compress&cs=tinysrgb&w=600',
    duration: '10:24',
    publisher: 'CodeWithMosh',
    publishedAt: '2023-11-15',
    views: '1.2M',
  },
  {
    id: '2',
    title: 'Finding and Fixing JavaScript Bugs',
    url: 'https://www.youtube.com/watch?v=example2',
    thumbnailUrl: 'https://images.pexels.com/photos/577585/pexels-photo-577585.jpeg?auto=compress&cs=tinysrgb&w=600',
    duration: '15:37',
    publisher: 'Traversy Media',
    publishedAt: '2023-10-21',
    views: '856K',
  },
  {
    id: '3',
    title: 'Debugging in VS Code: Tips and Tricks',
    url: 'https://www.youtube.com/watch?v=example3',
    thumbnailUrl: 'https://images.pexels.com/photos/270404/pexels-photo-270404.jpeg?auto=compress&cs=tinysrgb&w=600',
    duration: '12:08',
    publisher: 'VS Code Tips',
    publishedAt: '2023-09-05',
    views: '453K',
  },
  {
    id: '4',
    title: 'Common React Bugs and Solutions',
    url: 'https://www.youtube.com/watch?v=example4',
    thumbnailUrl: 'https://images.pexels.com/photos/4709289/pexels-photo-4709289.jpeg?auto=compress&cs=tinysrgb&w=600',
    duration: '22:15',
    publisher: 'React Masters',
    publishedAt: '2023-08-14',
    views: '328K',
  },
  {
    id: '5',
    title: 'Debugging for Beginners',
    url: 'https://www.youtube.com/watch?v=example5',
    thumbnailUrl: 'https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&cs=tinysrgb&w=600',
    duration: '8:45',
    publisher: 'Programming with Mosh',
    publishedAt: '2023-07-22',
    views: '1.5M',
  },
];

// Mock news search results
export const mockNewsResults: NewsResult[] = [
  {
    id: '1',
    title: 'Major Security Bug Found in Popular Framework',
    url: 'https://techcrunch.com/example-article-1',
    snippet: 'Researchers have discovered a critical security vulnerability in a widely-used framework that could affect millions of websites.',
    imageUrl: 'https://images.pexels.com/photos/60504/security-protection-anti-virus-software-60504.jpeg?auto=compress&cs=tinysrgb&w=600',
    source: 'TechCrunch',
    publishedAt: '2023-11-28',
  },
  {
    id: '2',
    title: 'Tech Giant Releases New Debugging Tools',
    url: 'https://theverge.com/example-article-2',
    snippet: 'The company announced a suite of new debugging tools aimed at helping developers find and fix bugs more efficiently.',
    imageUrl: 'https://images.pexels.com/photos/577585/pexels-photo-577585.jpeg?auto=compress&cs=tinysrgb&w=600',
    source: 'The Verge',
    publishedAt: '2023-11-25',
  },
  {
    id: '3',
    title: 'Study Shows Most Expensive Software Bugs in History',
    url: 'https://wired.com/example-article-3',
    snippet: 'A new study has compiled the most costly software bugs in history, with some causing billions in damages.',
    source: 'Wired',
    publishedAt: '2023-11-20',
  },
  {
    id: '4',
    title: 'New AI Tool Can Predict Code Bugs Before They Happen',
    url: 'https://techradar.com/example-article-4',
    snippet: 'Researchers have developed an AI system that can predict potential bugs in code before they\'re even written.',
    imageUrl: 'https://images.pexels.com/photos/2582937/pexels-photo-2582937.jpeg?auto=compress&cs=tinysrgb&w=600',
    source: 'TechRadar',
    publishedAt: '2023-11-18',
  },
  {
    id: '5',
    title: 'Bug Bounty Programs See Record Payouts in 2023',
    url: 'https://zdnet.com/example-article-5',
    snippet: 'Companies are paying out record amounts to security researchers who find vulnerabilities in their software.',
    source: 'ZDNet',
    publishedAt: '2023-11-15',
  },
];

// Mock map search results
export const mockMapResults: MapResult[] = [
  {
    id: '1',
    name: 'Bug Hunters Software Solutions',
    address: '123 Tech Lane, San Francisco, CA 94107',
    coordinates: {
      lat: 37.7749,
      lng: -122.4194,
    },
    rating: 4.8,
    category: 'Software Company',
  },
  {
    id: '2',
    name: 'Debuggers Cafe',
    address: '456 Coding Blvd, New York, NY 10001',
    coordinates: {
      lat: 40.7128,
      lng: -74.0060,
    },
    rating: 4.5,
    category: 'Cafe',
  },
  {
    id: '3',
    name: 'The Bug Fix Repair Shop',
    address: '789 Developer Ave, Seattle, WA 98101',
    coordinates: {
      lat: 47.6062,
      lng: -122.3321,
    },
    rating: 4.2,
    category: 'Computer Repair',
  },
  {
    id: '4',
    name: 'BugBytes Bookstore',
    address: '101 Programming Pkwy, Austin, TX 78701',
    coordinates: {
      lat: 30.2672,
      lng: -97.7431,
    },
    rating: 4.7,
    category: 'Bookstore',
  },
  {
    id: '5',
    name: 'Syntax Error Bar & Grill',
    address: '202 Compiler St, Boston, MA 02110',
    coordinates: {
      lat: 42.3601,
      lng: -71.0589,
    },
    rating: 4.3,
    category: 'Restaurant',
  },
];